export const filterStripConfig = [
  {
    id: 1,
    name: "Invoice Status",
    key: "Invoice Status",
    placeholder: "Please select status",
    isDisabled: false,
    isClearable: true,
    isRequired: false,
    isSearchable: false,
    value: [{ label: "Fully paid", value: "Fully paid" }],
    options: [
      { label: "Payment Pending", value: "Payment pending" },
      { label: "In dispute", value: "In dispute" },
      { label: "Partially paid", value: "Partially paid" },
      { label: "Fully paid", value: "Fully paid" },
    ],
    isMulti: true,
    preSelected: true,
    componentType: "multi-select",
  },
  {
    id: 2,
    name: "Issued date Range",
    key: "Issued date Range",
    placeholder: "Please select date range",
    isDisabled: false,
    isClearable: true,
    isRequired: false,
    isSearchable: false,
    value: [],
    options: [
      { label: "Today", value: "Today" },
      { label: "Last 7 Days", value: "Last 7 Days" },
      { label: "Last 30 Days", value: "Last 30 Days" },
      { label: "Last 90 Days", value: "Last 90 Days" },
    ],
    isMulti: false,
    preSelected: false,
    componentType: "select",
    isDateField: true,
  },
  {
    id: 3,
    name: "Current Due and Overdue",
    key: "Current Due and Overdue",
    placeholder: "Please select due",
    isDisabled: false,
    isClearable: true,
    isRequired: false,
    isSearchable: false,
    value: [],
    options: [
      { label: "All Dues", value: "all" },
      { label: "Current Dues", value: "current" },
      { label: "Overdue Dues", value: "overdue" },
      { label: "Past Due", value: "past_due" },
      { label: "Upcoming Dues", value: "upcoming" },
      { label: "Paid Dues", value: "paid" },
      { label: "Unpaid Dues", value: "unpaid" },
      { label: "Last Month's Dues", value: "last_month" },
      { label: "Custom Date Range", value: "custom" },
      { label: "Dues by Category", value: "by_category" },
    ],
    isMulti: false,
    preSelected: false,
    componentType: "select",
  },
  {
    id: 4,
    name: "Followup status",
    key: "Followup status",
    placeholder: "Please select followup status",
    isDisabled: false,
    isClearable: true,
    isRequired: false,
    isSearchable: false,
    value: [],
    options: [
      { label: "All Followups", value: "all" },
      { label: "Pending", value: "pending" },
      { label: "Completed", value: "completed" },
      { label: "Overdue", value: "overdue" },
      { label: "Upcoming", value: "upcoming" },
    ],
    isMulti: false,
    preSelected: false,
    componentType: "select",
  },
  {
    id: 5,
    name: "Last activity",
    key: "Last activity",
    placeholder: "Please select last activity",
    isDisabled: false,
    isClearable: true,
    isRequired: false,
    isSearchable: false,
    value: [],
    options: [
      { label: "Any Activity", value: "any" },
      { label: "Email Sent", value: "email_sent" },
      { label: "Call Made", value: "call_made" },
      { label: "Meeting Held", value: "meeting_held" },
      { label: "Note Added", value: "note_added" },
      { label: "Task Completed", value: "task_completed" },
    ],
    isMulti: false,
    preSelected: false,
    componentType: "select",
  },
];
